version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:mysql://db:3306/adopet_api
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=adopet_api
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-data:
